### ISSUE TITLE
Failed to Load Error

### ISSUE THREAD

**Issue by Snipe3000** [Jeshibu/Playnite-OculusLibrary#1] opened 2023-04-20 02:52 UTC
I'm getting an error when I load this extension:

Extension "Oculus Library Importer" Failed to load properly.

**Comment by Caddie2908** [comment] 2023-04-22 08:58
Same here. Oculus app was opened, but games and programs will not be found by playnite launcher

**Comment by Jock90** [comment] 2023-05-30 11:57
I'm getting the same error. Can the developer please check this out?
The Playnite error details are...

Playnite 10.16

Addons/Installed/Libraries I see an entry "Oculus Library Importer" and clicking on it displays "Extension failed to load properly".

In the playnite "extensions.log" I see...
30-05 11:06:09.010|ERROR|OculusLibrary#OculusLibraryPlugin:Error in OculusLibraryPlugin constructor
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at OculusLibrary.OculusLibrarySettingsViewModel.SeedRevivePath() in D:\a\Playnite-OculusLibrary\Playnite-OculusLibrary\OculusLibrary\OculusLibrarySettings.cs:line 53
   at OculusLibrary.OculusLibrarySettingsViewModel..ctor(OculusLibraryPlugin plugin, IPlayniteAPI playniteApi) in D:\a\Playnite-OculusLibrary\Playnite-OculusLibrary\OculusLibrary\OculusLibrarySettings.cs:line 39
   at OculusLibrary.OculusLibraryPlugin..ctor(IPlayniteAPI api) in D:\a\Playnite-OculusLibrary\Playnite-OculusLibrary\OculusLibrary\OculusLibraryPlugin.cs:line 42

In the "playnite.log" file I see...
30-05 11:06:09.030|ERROR|ExtensionFactory:Failed to load plugin: Oculus Library Importer
System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at OculusLibrary.OculusLibrarySettingsViewModel.SeedRevivePath() in D:\a\Playnite-OculusLibrary\Playnite-OculusLibrary\OculusLibrary\OculusLibrarySettings.cs:line 53
   at OculusLibrary.OculusLibrarySettingsViewModel..ctor(OculusLibraryPlugin plugin, IPlayniteAPI playniteApi) in D:\a\Playnite-OculusLibrary\Playnite-OculusLibrary\OculusLibrary\OculusLibrarySettings.cs:line 39
   at OculusLibrary.OculusLibraryPlugin..ctor(IPlayniteAPI api) in D:\a\Playnite-OculusLibrary\Playnite-OculusLibrary\OculusLibrary\OculusLibraryPlugin.cs:line 51

**Comment by Jeshibu** [comment] 2023-10-25 06:21
Completely missed this, sorry. This should be fixed as of 2.4.1.

**Closed as completed** 2023-10-25 06:21 UTC

**Comment by Snipe3000** [comment] 2023-10-25 07:09
Even after the update, it still errors out with 2.4.1 installed

25-10 00:12:31.849|INFO |MainViewModelBase:Importing games from Oculus plugin.
25-10 00:12:32.221|ERROR|MainViewModelBase:Failed to import games from plugin: Oculus
System.Net.WebException: The request was aborted: The connection was closed unexpectedly.
   at System.Net.ConnectStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.HttpWebRequest.MakeMemoryStream(Stream stream)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OculusLibrary.DataExtraction.WebClientWrapper.<UploadValuesAsync>d__5.MoveNext() in D:\a\Playnite-OculusLibrary\Playnite-OculusLibrary\OculusLibrary\DataExtraction\WebClientWrapper.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OculusLibrary.DataExtraction.OculusApiScraper.<GetJsonData>d__6.MoveNext() in D:\a\Playnite-OculusLibrary\Playnite-OculusLibrary\OculusLibrary\DataExtraction\OculusApiScraper.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OculusLibrary.DataExtraction.OculusApiScraper.<GetMetadata>d__7.MoveNext() in D:\a\Playnite-OculusLibrary\Playnite-OculusLibrary\OculusLibrary\DataExtraction\OculusApiScraper.cs:line 40

**Comment by Jeshibu** [comment] 2023-10-25 18:59
Thanks @Snipe3000 - could you specify what country you live, and what URL you get redirected to if you open this? https://www.meta.com/experiences/pcvr/

The issue is about the collection of metadata from meta.com (moved from oculus.com) and it being finicky about locales.

**Comment by Snipe3000** [comment] 2023-10-25 19:38
> Thanks @Snipe3000 - could you specify what country you live, and what URL you get redirected to if you open this? https://www.meta.com/experiences/pcvr/
> 
> The issue is about the collection of metadata from meta.com (moved from oculus.com) and it being finicky about locales.

USA,
I get the same URL when I go there: https://www.meta.com/experiences/pcvr/

**Comment by Jeshibu** [comment] 2023-10-25 19:46
really? there's no `en-us` in there?

**Comment by Snipe3000** [comment] 2023-10-25 19:50
> really? there's no `en-us` in there?

Nope

**Comment by Jeshibu** [comment] 2023-11-12 19:48
Latest release should fix the import erroring out at least, but I'm still struggling to understand why USA requests are getting aborted by the meta website when requesting metadata (to get the name, among other things). So while it'll import now, the game names will be busted, and metadata is limited to cover/icon/background.
This is a hopefully temporary partial fix while I figure out the metadata request problem.

**Comment by Snipe3000** [comment] 2023-11-13 19:47
Looks like its not broken anymore, but like you said, the names and the rest of the metadata is busted.
